# Generated by Django 3.0.4 on 2020-08-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civel',
            name='beneficiosCivel',
            field=models.CharField(choices=[('Consumidor', 'Consumidor'), ('Familia', 'Familia'), ('Cobranças', 'Cobranças'), ('Responsabilidade Civil', 'Responsabilidade Civil')], max_length=100),
        ),
    ]
