# Generated by Django 3.0.4 on 2020-08-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civels', '0004_auto_20200827_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civel',
            name='cpfCivel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='civel',
            name='whatsAppCivel',
            field=models.CharField(max_length=11),
        ),
    ]
