# Generated by Django 3.0.4 on 2020-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civels', '0005_auto_20200827_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civel',
            name='tiposBeneficiosCivel',
            field=models.CharField(blank=True, choices=[('Alimentos', 'Alimentos'), ('Divórcio', 'Divórcio'), ('Inventários', 'Inventários'), ('Investigação de paternidade', 'Investigação de paternidade'), ('Interdição', 'Interdição'), ('Recuperação de Créditos', 'Recuperação de Créditos'), ('Busca e Apreensão', 'Busca e Apreensão'), ('Revisional de Financiamentos', 'Revisional de Financiamentos'), ('Sem tipo', 'Sem tipo')], max_length=100, null=True),
        ),
    ]
