# Generated by Django 3.0.4 on 2020-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Previdenciario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePrev', models.CharField(max_length=255)),
                ('cpfPrev', models.CharField(max_length=11)),
                ('whatsAppPrev', models.CharField(max_length=9)),
                ('beneficiosPrev', models.CharField(choices=[('Aposentadoria por Idade', 'Aposentadoria por Idade'), ('Aposentadoria por Tempo de Contribuição', 'Aposentadoria por Tempo de Contribuição'), ('Aposentadoria por Invalidez', 'Aposentadoria por Invalidez'), ('Pensão por Morte', 'Pensão por Morte'), ('Auxilio Doença', 'Auxilio Doença'), ('Auxilio Reclusão', 'Auxilio Reclusão'), ('Auxilio Maternidade', 'Auxilio Maternidade'), ('Benefícios Assistenciais', 'Benefícios Assistenciais'), ('Abono Anual', 'Abono Anual'), ('Revisão de Beneficio', 'Revisão de Beneficio'), ('Auxilio Acidente', 'Auxilio Acidente')], max_length=100)),
                ('advogadoPrev', models.CharField(choices=[('Dr. Itiel', 'Dr. Itiel')], max_length=255)),
                ('protocoloPrev', models.CharField(max_length=255)),
                ('statusDocPrev', models.CharField(choices=[('Pendente', 'Pendente'), ('Completo', 'Completo')], max_length=100)),
                ('docPrev', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('criadoPrev', models.DateTimeField(auto_now_add=True)),
                ('modificadoPrev', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
