# Generated by Django 3.0.4 on 2020-08-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('previdenciarios', '0002_auto_20200826_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previdenciario',
            name='cpfPrev',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='previdenciario',
            name='protocoloPrev',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='previdenciario',
            name='whatsAppPrev',
            field=models.IntegerField(max_length=11),
        ),
    ]
