# Generated by Django 3.0.4 on 2020-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalhista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTrab', models.CharField(max_length=255)),
                ('cpfTrab', models.CharField(max_length=11)),
                ('whatsAppTrab', models.CharField(max_length=11)),
                ('beneficiosTrab', models.CharField(choices=[('Trabalhista', 'Trabalhista')], max_length=100)),
                ('advogadoTrab', models.CharField(choices=[('Dr. Itiel', 'Dr. Itiel')], max_length=255)),
                ('protocoloTrab', models.CharField(max_length=100)),
                ('statusDocTrab', models.CharField(choices=[('Pendente', 'Pendente'), ('Completo', 'Completo')], max_length=100)),
                ('docTrab', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('criadoTrab', models.DateTimeField(auto_now_add=True)),
                ('modificadoTrab', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
